"""replace archived_at with archived

Revision ID: 50140cf556bd
Revises: ee299dfb12d1
Create Date: 2026-10-01 15:44:50.819215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50140cf556bd'
down_revision: Union[str, Sequence[str], None] = 'ee299dfb12d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived', sa.Boolean(), server_default='0', nullable=False))
        batch_op.drop_column('archived_at')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('archived_at', sa.DATETIME(), nullable=True))
        batch_op.drop_column('archived')

    # ### end Alembic commands ###
